name: build Docker Image

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Show Version
        run: |
          echo "VERSION=$(cat VERSION)" >> "$GITHUB_ENV"

      - name: Set up QEMU for ARM Emulation
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag "action-cfn-lint:$(date +%s)" \
            .

      - name: Publish to Docker Hub
        run: |
          printenv PASSWORD | docker login -u "$USERNAME" --password-stdin
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag "$REPOSITORY:$VERSION" \
            --push \
            .
          docker logout
        env:
          REPOSITORY: ${{ github.repository }}
          USERNAME: ${{ secrets.username }}
          PASSWORD: ${{ secrets.password }}

      - name: Publish to GitHub Container Registry
        run: |
          printenv PASSWORD | docker login ghcr.io --username "$USERNAME" --password-stdin
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag "ghcr.io/$REPOSITORY:$VERSION" \
            --push \
            .
          docker logout ghcr.io
        env:
          REPOSITORY: ${{ github.repository }}
          USERNAME: ${{ github.repository_owner }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
