name: Release

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

env:
  VERSION: 0.0.0
  IMAGE_NAME: cfn-lint

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Show Version
        run: |
          echo "VERSION=$(cat VERSION)" >> "$GITHUB_ENV"

      - id: build
        name: Build and push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ vars.USERNAME }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
